<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-3JC72G1" name="reRunTest.ReRunFailedTest" tests="4" failures="1" timestamp="2023-06-08T17:59:05 IST" time="55.769" errors="0">
  <testcase name="fbLog" time="17.247" classname="reRunTest.ReRunFailedTest">
    <skipped/>
  </testcase> <!-- fbLog -->
  <system-out/>
  <testcase name="fbLog" time="12.898" classname="reRunTest.ReRunFailedTest">
    <failure type="java.lang.AssertionError" message="expected [Facebook – log in or sign up] but found [Log in to Facebook]">
      <![CDATA[java.lang.AssertionError: expected [Facebook – log in or sign up] but found [Log in to Facebook]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at reRunTest.ReRunFailedTest.fbLog(ReRunFailedTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- fbLog -->
  <system-out/>
  <testcase name="fbLog" time="12.308" classname="reRunTest.ReRunFailedTest">
    <skipped/>
  </testcase> <!-- fbLog -->
  <system-out/>
  <testcase name="fbLog" time="13.316" classname="reRunTest.ReRunFailedTest">
    <skipped/>
  </testcase> <!-- fbLog -->
  <system-out/>
</testsuite> <!-- reRunTest.ReRunFailedTest -->
